// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ai_Assistent
{
    internal sealed partial class Vsix
    {
        public const string Id = "Ai_Assistent.d1ab76b9-033e-482f-b5d8-8681d6a85321";
        public const string Name = "Ai_Assistent";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma";
        public const string Tags = "";
    }
}
